title: Blog de Sergio Naito - Primeiro Blog
description: Este é o meu primeiro blog baseado no blog de Lang Haul.
url: https://long-haul.netlify.app
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Início
      url: /index.html
    - title: Sobre
      url: /about
    - title: Contato
      url: /contact

social:
    github: sergio-naito
    twitter: sergionait89390
    facebook: brianmaierjr
    email: sernaito@gmail.com 
    linkedin: sergio-naito-156ab893

google_analytics: "UA-58263416-1"

disqus:
    shortname: sergio-naito
